CREATE TABLE generation_tasks (
    id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    model VARCHAR(128) NOT NULL,
    request_json LONGTEXT NOT NULL,
    state VARCHAR(32) NOT NULL,
    remote_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    source_url TEXT NULL,
    artifact_key VARCHAR(255) NULL,
    artifact_size BIGINT NULL,
    artifact_sha256 VARCHAR(64) NULL,
    error_code VARCHAR(64) NULL,
    attempts INT NOT NULL DEFAULT 0,
    recoverable BOOLEAN NOT NULL DEFAULT FALSE,
    next_run_at BIGINT NOT NULL,
    lease_token VARCHAR(36) NULL,
    lease_until BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_generation_idempotency (user_id, idempotency_key),
    UNIQUE KEY uk_generation_remote (provider, remote_id),
    KEY idx_generation_due (state, next_run_at, lease_until),
    KEY idx_generation_owner (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
