spring.task.scheduling.pool.size=3
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
spring.flyway.baseline-on-migrate=false
composition.ffmpeg-dir=${FFMPEG_DIR:}
composition.font-path=${COMPOSITION_FONT_PATH:}
